[package]
name = "multi-llm-rust-app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

tao = "0.27.0"
winit = "0.29.15"
wry = "0.39.0"
